### ISSUE TITLE
Case 0 ... 1ms Error

### ISSUE THREAD

**Issue by AkashChandrakar** [seri/gettc#15]
[gettc] Compile solver
[gettc] Compile checker
[gettc] Run test cases
Case 0 ... 1ms Error
Case 1 ... 1ms Error
Case 2 ... 1ms Error
[gettc] Summary
3 cases checked, 0 failures, 3 errors
 Errors: 0, 1, 2
    Total time taken: 3 ms
    Average time taken: 1 ms
    Slowest running case: 1 ms (case 0)

**Comment by seri** [comment]
Which problem ID got you this error?

**Comment by seri** [comment]
Can you paste the output for the `Compile solver` and `Compile checker` sections? They must be compiled the first time you run `make demo`. You can force a recompile by `make clean` and then `make demo`.

**Comment by AkashChandrakar** [comment]
make demo
[gettc] Compile solver
g++ -std=gnu++0x -I/home/akash/.gettc/include/cpp -o ../../build/cpp/AaagmnrsRunner AaagmnrsRunner.cpp
[gettc] Compile checker
[gettc] Run test cases
Case 0 ... 1ms Error
Case 1 ... 1ms Error
Case 2 ... 1ms Error
[gettc] Summary
3 cases checked, 0 failures, 3 errors
 Errors: 0, 1, 2
    Total time taken: 3 ms
    Average time taken: 1 ms
    Slowest running case: 1 ms (case 0)

**Comment by seri** [comment]
I see. When you look at the directory `Aaagmnrs/build/cpp/demo`, do you see the files `0.out`, `1.out`, `2.out`? Do they all contain just the string `[]`?

**Comment by AkashChandrakar** [comment]
yes the files are present.
content of 0.in file [ "Aaagmnrs", "TopCoder", "anagrams", "Drop Cote" ]
content of 0.out file [ "Aaagmnrs",  "TopCoder" ]

**Comment by seri** [comment]
These are the files in `Aaagmnrs/data/demo`. I'm interested in those in `Aaagmnrs/build/cpp/demo`, which should be generated after `make demo`.

**Comment by AkashChandrakar** [comment]
No files are generated in directory Aaagmnrs/build/cpp/demo after make demo.

**Comment by seri** [comment]
I see. I suppose `Aaagmnrs/build/cpp/AaagmnrsRunner` is generated and executable? Can you run it manually like `./AaagmnrsRunner ../../data/demo/0.in 0.out` and is a file `0.out` generated with the content `[]`?

**Comment by AkashChandrakar** [comment]
I found the solution executable are generated but they don't executable permission when I am on some other Drive. I am on ubuntu and if I download the problem in  drive where I installed windows or any other drive with NTFS partation the xecutable are generated but they don't executable permission.But when I download the same problem on my home folder of ubuntu I don't get any error.

**Comment by seri** [comment]
I would consider it solved then :)
