### ISSUE TITLE
java character input parameter is not in the right format in sys/*.in files

### ISSUE THREAD

**Issue by agsha** [seri/gettc#17]
Steps to reproduce

download ContextFreeGrammar (problem id: 6210) and run systests

    gettc 6210
    ant sys

basically characters are not enclosed in single quotes

**Comment by seri** [comment]
Hi Sharath, we talked over email. I tried the steps just now. Yes, I confirm that it's a bug. I'll fix it soon.

**Comment by seri** [comment]
This appears to be inconsistent behavior from TopCoder's part. The example tests are okay for 6210, but the systests: http://community.topcoder.com/stat?c=problem_solution&cr=11829284&rd=9822&pm=6210 are not. Gettc's parsers can try working around that (by allowing a character to be 'X' OR X), but I'm not sure it's worth it if 6210 is the only problem that has this issue.

**Comment by seri** [comment]
I decided it's worth it and did the fix. Enjoy.
