### ISSUE TITLE
unable to download problem description

### ISSUE THREAD

**Issue by rajneesh0** [seri/gettc#18]
![screenshot from 2015-11-06 23 20 57](https://cloud.githubusercontent.com/assets/3881810/11004273/4c97d598-84dd-11e5-81b3-fb8f27c25d44.png)
![screenshot from 2015-11-06 23 21 21](https://cloud.githubusercontent.com/assets/3881810/11004274/4ca4e5da-84dd-11e5-8651-16992b84b926.png)

**Comment by seri** [comment]
I can confirm this issue. Topcoder has probably changed their log-in mechanism recently. I'm busy at the moment but I'll get back to it as soon as I can.

**Comment by gaddevarunteja** [comment]
Can you please resolve this issue quickly

**Comment by seri** [comment]
@rajneesh0  @gaddevarunteja  I'll try to find time every now and then. May take a week or two from now. Stay tuned.

**Comment by seri** [comment]
@webglider @rajneesh0 @gaddevarunteja I've fixed this. Please update your version with `gem install gettc`. Run `gettc version` again to make sure it's updated to 2.0 and you should be good to go.
